$path = "d:\Full stack\Local projects\Retailer shops - pos\src\main\main.ts"
$lines = Get-Content $path
$newLines = @()
for ($i = 0; $i -lt 1140; $i++) { $newLines += $lines[$i] }

# The new content
$newLines += "// ============= EVENT LISTENERS ============="
$newLines += ""
$newLines += "// --- ACTIVATION LOGIC ---"
$newLines += "// License Format: Base64 JSON { businessName, plan, durationDays, licenseId }"
$newLines += "function verifyActivationKey(name: string, key: string): { valid: boolean, license: any } {"
$newLines += "  if (!name || !key) return { valid: false, license: null };"
$newLines += "  try {"
$newLines += "    const decoded = Buffer.from(key, 'base64').toString('utf8');"
$newLines += "    const license = JSON.parse(decoded);"
$newLines += ""
$newLines += "    // New JSON System Validation"
$newLines += "    if (license.businessName && license.businessName.toLowerCase() === name.toLowerCase() && license.durationDays) {"
$newLines += "      return { valid: true, license };"
$newLines += "    } else {"
$newLines += "      logger.warn('License name mismatch or missing duration: Expected ' + name + ', Got ' + license.businessName + '. Duration: ' + license.durationDays);"
$newLines += "    }"
$newLines += ""
$newLines += "    return { valid: false, license: null };"
$newLines += "  } catch (e) {"
$newLines += "    logger.debug('Key is not valid JSON Base64, trying legacy MD5 fallback...');"
$newLines += "    // If JSON parsing fails, try old MD5 method as fallback"
$newLines += "    try {"
$newLines += "      const cleanName = name.trim().toLowerCase();"
$newLines += "      const firstName = cleanName.split(/\s+/)[0].replace(/[^a-z0-9]/g, '');"
$newLines += "      const parts = key.split('-');"
$newLines += "      if (parts.length === 3) {"
$newLines += "        const year = parts[1];"
$newLines += "        const hash = crypto.createHash('md5').update(cleanName).digest('hex').substring(0, 4);"
$newLines += "        if (key === (firstName + '-' + year + '-' + hash)) {"
$newLines += "          logger.info('Legacy MD5 license verified.');"
$newLines += "          return { valid: true, license: { plan: 'lifetime', isLegacy: true } };"
$newLines += "        }"
$newLines += "      }"
$newLines += "    } catch { return { valid: false, license: null }; }"
$newLines += "    return { valid: false, license: null };"
$newLines += "  }"
$newLines += "}"
$newLines += ""
$newLines += "ipcMain.handle('is-activated', async () => {"
$newLines += "  try {"
$newLines += "    if (!db || !licenseManager) throw new Error('Systems not initialized');"
$newLines += "    "
$newLines += "    // Check V2 system first"
$newLines += "    const v2Result = await licenseManager.validateLocalLicense();"
$newLines += "    if (v2Result.valid) {"
$newLines += "      return { success: true, activated: true, license: v2Result.data };"
$newLines += "    }"
$newLines += ""
$newLines += "    // Fallback to legacy check"
$newLines += "    const settings = db.prepare('SELECT activation_key, business_name, expiry_date FROM settings WHERE id = 1').get() as any;"
$newLines += ""
$newLines += "    if (!settings || !settings.activation_key || !settings.business_name) {"
$newLines += "      return { success: true, activated: false, license: null };"
$newLines += "    }"
$newLines += ""
$newLines += "    const { valid, license } = verifyActivationKey(settings.business_name, settings.activation_key);"
$newLines += "    "
$newLines += "    if (valid && license && !license.isLegacy) {"
$newLines += "      if (settings.expiry_date) {"
$newLines += "        license.expiry = settings.expiry_date;"
$newLines += "      }"
$newLines += "    }"
$newLines += ""
$newLines += "    return { success: true, activated: valid, license };"
$newLines += "  } catch (error: any) {"
$newLines += "    return { success: false, error: error.message };"
$newLines += "  }"
$newLines += "});"
$newLines += ""
$newLines += "ipcMain.handle('activate-app', async (_, { businessName, activationKey }: { businessName: string, activationKey: string }) => {"
$newLines += "  try {"
$newLines += "    if (!db) throw new Error('Database not initialized');"
$newLines += ""
$newLines += "    const { valid, license } = verifyActivationKey(businessName, activationKey);"
$newLines += "    if (!valid) {"
$newLines += "      throw new Error('Invalid activation key for this business name');"
$newLines += "    }"
$newLines += ""
$newLines += "    const settings = db.prepare('SELECT expiry_date, used_license_ids FROM settings WHERE id = 1').get() as any;"
$newLines += ""
$newLines += "    if (license.isLegacy) {"
$newLines += "      db.prepare('UPDATE settings SET business_name = ?, activation_key = ? WHERE id = 1')"
$newLines += "        .run(businessName, activationKey);"
$newLines += "      logger.info('Legacy app activated for: ' + businessName);"
$newLines += "      return { success: true };"
$newLines += "    }"
$newLines += ""
$newLines += "    // Additive logic for new JSON keys"
$newLines += "    let usedIds: string[] = [];"
$newLines += "    try { usedIds = JSON.parse(settings.used_license_ids || '[]'); } catch (e) { }"
$newLines += ""
$newLines += "    if (usedIds.includes(license.licenseId)) {"
$newLines += "      throw new Error('This license key has already been used.');"
$newLines += "    }"
$newLines += ""
$newLines += "    usedIds.push(license.licenseId);"
$newLines += ""
$newLines += "    const now = new Date();"
$newLines += "    let currentExpiry: Date;"
$newLines += ""
$newLines += "    if (!settings.expiry_date || settings.expiry_date === 'lifetime') {"
$newLines += "      currentExpiry = now;"
$newLines += "    } else {"
$newLines += "      currentExpiry = new Date(settings.expiry_date);"
$newLines += "      if (isNaN(currentExpiry.getTime()) || currentExpiry < now) {"
$newLines += "        currentExpiry = now;"
$newLines += "      }"
$newLines += "    }"
$newLines += ""
$newLines += "    currentExpiry.setDate(currentExpiry.getDate() + license.durationDays);"
$newLines += "    const newExpiryIso = currentExpiry.toISOString();"
$newLines += ""
$newLines += "    db.prepare('UPDATE settings SET business_name = ?, activation_key = ?, expiry_date = ?, used_license_ids = ? WHERE id = 1')"
$newLines += "      .run(businessName, activationKey, newExpiryIso, JSON.stringify(usedIds));"
$newLines += ""
$newLines += "    logger.info('App activated for: ' + businessName + '. Added ' + license.durationDays + ' days. New expiry: ' + newExpiryIso);"
$newLines += "    return { success: true };"
$newLines += "  } catch (error: any) {"
$newLines += "    logger.error('Activation failed:', error);"
$newLines += "    return { success: false, error: error.message };"
$newLines += "  }"
$newLines += "});"
$newLines += ""
$newLines += "ipcMain.handle('get-fingerprint', async () => {"
$newLines += "  try {"
$newLines += "    if (!licenseManager) throw new Error('License manager not initialized');"
$newLines += "    const fingerprint = await licenseManager.getDeviceFingerprint();"
$newLines += "    return { success: true, data: fingerprint };"
$newLines += "  } catch (error: any) {"
$newLines += "    return { success: false, error: error.message };"
$newLines += "  }"
$newLines += "});"
$newLines += ""
$newLines += "ipcMain.handle('activate-app-v2', async (_, licenseKey: string) => {"
$newLines += "  try {"
$newLines += "    if (!licenseManager) throw new Error('License manager not initialized');"
$newLines += "    return await licenseManager.activateLicense(licenseKey);"
$newLines += "  } catch (error: any) {"
$newLines += "    return { success: false, error: error.message };"
$newLines += "  }"
$newLines += "});"
$newLines += ""
$newLines += "ipcMain.handle('generate-license-key', async (_, data: any) => {"
$newLines += "  try {"
$newLines += "    if (!licenseManager) throw new Error('License manager not initialized');"
$newLines += "    const licenseKey = licenseManager.encryptLicense(data);"
$newLines += "    return { success: true, data: licenseKey };"
$newLines += "  } catch (error: any) {"
$newLines += "    return { success: false, error: error.message };"
$newLines += "  }"
$newLines += "});"
$newLines += ""
$newLines += "// ============= PRODUCT HANDLERS ============="
$newLines += ""
$newLines += "ipcMain.handle('get-products', async () => {"

for ($i = 1146; $i -lt $lines.Count; $i++) { $newLines += $lines[$i] }

$newLines | Set-Content $path
